### ISSUE TITLE
run_uchime is not working

### ISSUE THREAD

**Issue by tarunaaggarwal** [eukref/eukref#10]
Hello,

I'm running the `eukref_gbretrieve.py` script but am getting the following errors. The `temp_no_chimeras.fas` file that the script is not able to find is located in the same directory as the script and the file is not empty. In the script, the `infile` was closed after being read so I tried to resolve the issue by commenting out line 235 but no luck...Any suggestions as to how I can resolve this problem? Thank you!

```
Runing uchime on initial fasta file

Invalid command line
Option --uchime_ref is invalid
For list of command-line options use --help.

Traceback (most recent call last):
  File "eukref_gbretrieve.py", line 344, in <module>
    run_uchime('current_DB.fas', 'temp_initial_db.fas')
  File "eukref_gbretrieve.py", line 233, in run_uchime
    infile = open('temp_no_chimeras.fas')
IOError: [Errno 2] No such file or directory: 'temp_no_chimeras.fas'
```

**Comment by kolecko007** [comment]
Hi,

what version of usearch are you using? It seems usearch is commonly changing input options and ouput formats between versions. 

I suggest getting usearch 8.0.x..The script should work with that.

cheers
Martin

On 27 March 2017 22:00:01 CEST, Taruna <notifications@github.com> wrote:
>Hello,
>
>I'm running the `eukref_gbretrieve.py` script but am getting the
>following errors. The `temp_no_chimeras.fas` file that the script is
>not able to find is located in the same directory as the script and the
>file is not empty. In the script, the `infile` was closed after being
>read so I tried to resolve the issue by commenting out line 235 but no
>luck...Any suggestions as to how I can resolve this problem? Thank you!
>
>```
>Runing uchime on initial fasta file
>
>Invalid command line
>Option --uchime_ref is invalid
>For list of command-line options use --help.
>
>Traceback (most recent call last):
>  File "eukref_gbretrieve.py", line 344, in <module>
>    run_uchime('current_DB.fas', 'temp_initial_db.fas')
>  File "eukref_gbretrieve.py", line 233, in run_uchime
>    infile = open('temp_no_chimeras.fas')
>IOError: [Errno 2] No such file or directory: 'temp_no_chimeras.fas'
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/eukref/eukref/issues/10

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tarunaaggarwal** [comment]
Thank you. That fixed one problem but now I'm getting a blast error which probably also has to do with the version. Can the script work with other blast version? The oldest one we have on our cluster  is 2.2.25.

**Comment by kolecko007** [comment]
Hi,

can you please send me the error and few last lines of the ouput on the screen it giives you.

thank you,
Martin



On 27 March 2017 22:39:05 CEST, Taruna <notifications@github.com> wrote:
>Thank you. That fixed one problem but now I'm getting a blast error
>which probably also has to do with the version. Can the script work
>with other blast version? The oldest one we have on our cluster  is
>2.2.25. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eukref/eukref/issues/10#issuecomment-289578754

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tarunaaggarwal** [comment]
Sure! My command and the error are below.

Command:

```
python eukref_gbretrieve.py \
-i polychaeta_sorted_clustered_edited_correctHeaders.fasta \
-dbnt $NCBI_DB/nt \
-dbsi Reference_DB.fas \
-n 100 -p 8 -g Opisthokonta \
-m megablast -idsi 75 -idnt 90 -td tax_d.bin
```

Error:

```
Runing uchime on initial fasta file
sh: usearch: command not found
Removing short sequences from initial fasta file
starting cycle 1
running usearch
sh: usearch: command not found
sh: usearch: command not found
running blast
sh: blastn: command not found
Traceback (most recent call last):
  File "eukref_gbretrieve.py", line 370, in <module>
    'temp_DB_clust_500.blastntab')
  File "eukref_gbretrieve.py", line 117, in nt_blast
    infile = open(outf)
IOError: [Errno 2] No such file or directory: 'temp_DB_clust_500.blastntab'
```
